# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  -   repo: local
      hooks:
        - id: build-test-generate-native
          name: build & test & generate (+native)
          language: system
          entry: ./gradlew all nativeAll
          always_run: true
          pass_filenames: false